# Texter config file

# set language (en_us, id_id, ja_jp, ko_kr, ru_ru, tr_tr, zh_cn, vi_vn)
locale: en_us

# When set to true, update notification is displayed at startup
check.update: true

# If you want to disable the command, please set it to false
can.use.commands: true
